// Mocks generated by Mockito 5.4.2 from annotations
// in english_dictionary/test/core/feature/history/domain/usecases/save_history_word/save_history_word_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:english_dictionary/core/feature/history/core/errors/hisotry_failure.dart'
    as _i5;
import 'package:english_dictionary/core/feature/history/data/repositories/save_history_word/save_history_word_repository.dart'
    as _i3;
import 'package:english_dictionary/core/feature/history/domain/entities/history_word_entity.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SaveHistoryWordRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveHistoryWordRepository extends _i1.Mock
    implements _i3.SaveHistoryWordRepository {
  MockSaveHistoryWordRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.SaveHistoryWordFailure, _i6.HistoryWordEntity>>
      saveHistoryWord(_i6.HistoryWordEntity? entity) => (super.noSuchMethod(
            Invocation.method(
              #saveHistoryWord,
              [entity],
            ),
            returnValue: _i4.Future<
                _i2.Either<_i5.SaveHistoryWordFailure,
                    _i6.HistoryWordEntity>>.value(_FakeEither_0<
                _i5.SaveHistoryWordFailure, _i6.HistoryWordEntity>(
              this,
              Invocation.method(
                #saveHistoryWord,
                [entity],
              ),
            )),
          ) as _i4.Future<
              _i2.Either<_i5.SaveHistoryWordFailure, _i6.HistoryWordEntity>>);
}
