name: english_dictionary
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: '3.10.5'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  cloud_firestore: ^4.8.2
  flutter_bloc: ^8.1.3
  mockito: ^5.4.2
  get_it: ^7.6.0
  shared_preferences: ^2.1.2
  uuid: ^3.0.7
  equatable: ^2.0.5
  flutter_svg: ^2.0.7
  dartz: ^0.10.1
  google_sign_in: ^6.1.4
  google_fonts: ^5.1.0
  vibration: ^1.8.1
  faker: ^2.1.0
  dio: ^5.2.1+1
  pretty_dio_logger: ^1.3.1
  modal_bottom_sheet: ^3.0.0-pre
  intl: ^0.18.1
  flutter_tts: ^3.7.0
  image_picker: ^1.0.1
  lottie: ^2.4.0
  firebase_storage: ^11.2.5
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter



  flutter_lints: ^2.0.0
  build_runner: ^2.4.5


flutter:


  uses-material-design: true

  
  assets:
    - assets/icons/
    - assets/jsons/
    
  
  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

