// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALlxLx5PU5O5AL05O036Js8_W99onY7tw',
    appId: '1:571655594202:web:e7bc8f0f2721bdd34905e3',
    messagingSenderId: '571655594202',
    projectId: 'english-dictionary-7f559',
    authDomain: 'english-dictionary-7f559.firebaseapp.com',
    storageBucket: 'english-dictionary-7f559.appspot.com',
    measurementId: 'G-MYTJ8LZCNL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYSD_SGCtOLUqjVXrDKdPDKlMWEV7juVc',
    appId: '1:571655594202:android:5a02f89b5182e3e64905e3',
    messagingSenderId: '571655594202',
    projectId: 'english-dictionary-7f559',
    storageBucket: 'english-dictionary-7f559.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy44n1pRSYXHGdSTGcZXLV7XncR0-kY-0',
    appId: '1:571655594202:ios:c52df82cbfe2d2ad4905e3',
    messagingSenderId: '571655594202',
    projectId: 'english-dictionary-7f559',
    storageBucket: 'english-dictionary-7f559.appspot.com',
    iosClientId: '571655594202-io4dodqi3qooklhffbiq0hggpp3ndaot.apps.googleusercontent.com',
    iosBundleId: 'br.com.englishdictorionary.gcapps.englishDictionary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy44n1pRSYXHGdSTGcZXLV7XncR0-kY-0',
    appId: '1:571655594202:ios:2fdc8c8289dd10514905e3',
    messagingSenderId: '571655594202',
    projectId: 'english-dictionary-7f559',
    storageBucket: 'english-dictionary-7f559.appspot.com',
    iosClientId: '571655594202-6lto1s1jqcgp2dt3dol01ge92oglf8ip.apps.googleusercontent.com',
    iosBundleId: 'br.com.englishdictorionary.gcapps.englishDictionary.RunnerTests',
  );
}
