// Mocks generated by Mockito 5.4.2 from annotations
// in english_dictionary/test/core/feature/favorites/data/repositories/save_favorite_word/save_favorite_word_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:english_dictionary/core/feature/favorites/data/datasources/save_favorite_word/save_favorite_word_datasource.dart'
    as _i3;
import 'package:english_dictionary/core/feature/favorites/data/models/favorites_word_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFavoriteWordModel_0 extends _i1.SmartFake
    implements _i2.FavoriteWordModel {
  _FakeFavoriteWordModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SaveFavoriteWordDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveFavoriteWordDatasource extends _i1.Mock
    implements _i3.SaveFavoriteWordDatasource {
  MockSaveFavoriteWordDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.FavoriteWordModel> saveFavoriteWord(
          _i2.FavoriteWordModel? model) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveFavoriteWord,
          [model],
        ),
        returnValue:
            _i4.Future<_i2.FavoriteWordModel>.value(_FakeFavoriteWordModel_0(
          this,
          Invocation.method(
            #saveFavoriteWord,
            [model],
          ),
        )),
      ) as _i4.Future<_i2.FavoriteWordModel>);
}
