// Mocks generated by Mockito 5.4.2 from annotations
// in english_dictionary/test/core/feature/favorites/domain/usecases/get_words/get_words_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:english_dictionary/core/feature/words/core/errors/words_failure.dart'
    as _i4;
import 'package:english_dictionary/core/feature/words/data/repositories/get_words/get_words_repository.dart'
    as _i2;
import 'package:english_dictionary/core/feature/words/domain/entities/word_entity.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GetWordsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWordsRepository extends _i1.Mock
    implements _i2.GetWordsRepository {
  MockGetWordsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<(_i4.GetWordsFailure?, List<_i5.WordEntity>)> getWords() =>
      (super.noSuchMethod(
        Invocation.method(
          #getWords,
          [],
        ),
        returnValue:
            _i3.Future<(_i4.GetWordsFailure?, List<_i5.WordEntity>)>.value(
                (null, <_i5.WordEntity>[])),
      ) as _i3.Future<(_i4.GetWordsFailure?, List<_i5.WordEntity>)>);
}
