name: CI/CD

on:
  push:
    tags:
      - '*'


jobs: 
  flutter_test:
    permissions:
      id-token: write
      contents: read
      checks: write
    name: Run Flutter analyse and tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '12.x'
          cache: 'gradle'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - name: Install dependencies
        run: flutter pub get
      - name: Build runner - Generate code
        run: dart run build_runner build --delete-conflicting-outputs
      - name: Analyze and test
        run: flutter analyze && flutter test --coverage && flutter test --machine > tests-results.json
      - name: Upload coverage
        uses: dorny/test-reporter@v1.4.2
        with: 
          name: test-results
          path: tests-results.json
          reporter: flutter-json

  version:
      name: Create version number
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Install GitVersion
          uses: gittools/actions/gitversion/setup@v0.9.7
          with:
            versionSpec: "5.x"
        - name: Use GitVersion
          id: gitversion
          uses: gittools/actions/gitversion/execute@v0.9.7
        - name: Create version.txt with nuGetVersion
          run: echo ${{ steps.gitversion.outputs.nuGetVersion  }} > version.txt
        - name: Upload version.txt
          uses: actions/upload-artifact@v2
          with:
            name: gitversion
            path: version.txt